image: python:2

test:
  script:
    - pip install -r requirements.txt
    - DJANGO_SETTINGS_MODULE=spotofoweb.settings python manage.py migrate
    - DJANGO_SETTINGS_MODULE=spotofoweb.settings spotofo currently_playing

