# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotofoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('track', models.CharField(max_length=2048)),
                ('artist', models.CharField(max_length=2048)),
                ('album', models.CharField(max_length=2048)),
                ('track_uri', models.CharField(max_length=2048)),
                ('album_uri', models.CharField(max_length=2048)),
                ('artist_uri', models.CharField(max_length=2048)),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('json_string', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='spotofoweb.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='spotofoweb.SpotifyUser')),
                ('device_type', models.CharField(default='foo', max_length=2048)),
                ('username', models.CharField(default='foo', max_length=2048)),
                ('volume_percent', models.IntegerField(default=0)),
            ],
        ),
    ]
