# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotofoweb', '0003_auto_20170913_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
