# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotofoweb', '0004_auto_20170917_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authkey', models.CharField(max_length=2048, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authkeys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
